### ISSUE TITLE
Support for multiple packages

### ISSUE THREAD

**Issue by mehalter** [Roger-luo/IonCLI.jl#10]
I think in day to day use, it will become necessary to be able to run commands with several package names at once. Tasks such as: `ion add Plots DifferentialEquations Test` to be able to quickly add several packages at once.

This would be easy to implement once Comonicon adds support for Varargs (https://github.com/Roger-luo/Comonicon.jl/issues/26)

**Comment by Roger-luo** [comment]
true, thanks this is a good idea! I'll add this feature shortly

**Comment by Roger-luo** [comment]
just to clarify a bit (in case you find it slow), currently you will need to compile this package yourself since it's waiting for registration (so I cannot tag it) https://github.com/JuliaRegistries/General/pull/18652

The system image build CI will be triggered once it gets tagged.

Now if you don't build the system image yourself, it will have a slower start up time. Thus if you want to build the system image yourself, you can run

```julia
pkg> dev https://github.com/Roger-luo/IonCLI.jl.git
```

then

```sh
cd ~/.julia/IonCLI
julia --project deps/build.jl sysimg
julia --project deps/build.jl
```

this will install a fully compiled IonCLI that has the best startup time for you.

**Comment by Roger-luo** [comment]
should be supported via 0e44a9ce5f296fd4520a5edcb61f8a8d58d41f92
